---
- name: start helm
  command: helm init

- name: "wait for tiller-deploy ready status"
  command: >
    kubectl get pods --namespace=kube-system -l app=helm -o jsonpath='{.items[*].status.containerStatuses[*].ready}'
  register: tiller_ready_status
  # Wait for 10 minutes
  until: tiller_ready_status.stdout | match( '^(true\s)*true$' )
  retries: 120
  delay: 5

- name: "add KubeNow Helm repository"
  command: helm repo add charts https://kubenow.github.io/helm-charts/
