- name: create yaml directory
  file:
    path: "~/.kubernetes-yaml/shared-vol-nfs/"
    state: directory
    mode: 0755

- name: render shared-volume-nfs configuration
  template:
    src: shared-volume-nfs.yaml
    dest: "~/.kubernetes-yaml/shared-vol-nfs/shared-volume-nfs.yaml"

- name: create local-shared-volume (Kubernetes side)
  command: >
    kubectl apply -f "$HOME/.kubernetes-yaml/shared-vol-nfs/shared-volume-nfs.yaml"
