---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{name}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{storage}}
{% if storage_class_name is defined %}
  storageClassName: {{ storage_class_name }}
{% endif %}
