- name: create mountpath on node
  become: yes
  command: >
    mkdir "/mnt/data"

- name: mount hostdir on node
  become: yes
  command: >
    mount -t 9p -o trans=virtio,version=9p2000.L,rw data /mnt/data

- name: creatie yaml directory
  file:
    path: "~/.kubernetes-yaml/shared-vol-hostpath/"
    state: directory
    mode: 0755

- name: render local-shared-volume configuration
  template:
    src: local-shared-volume.yml
    dest: "~/.kubernetes-yaml/shared-vol-hostpath/local-shared-volume.yaml"

- name: create local-shared-volume (Kubernetes side)
  command: >
    kubectl apply -f "$HOME/.kubernetes-yaml/shared-vol-hostpath/local-shared-volume.yaml"
